---
defaults: &defaults
  docker:
    - image: circleci/python:3.6.1

version: 2
jobs:
  build:
    <<: *defaults

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: "Build Docker Image"
          command: |
              docker build -t $CIRCLE_PROJECT_REPONAME .

      - run:
          name: "Create workspace"
          command: |
              mkdir -p workspace/image
              docker save -o workspace/image/$CIRCLE_PROJECT_REPONAME-image.tar $CIRCLE_PROJECT_REPONAME:latest

      - persist_to_workspace:
          root: workspace
          paths:
            - image

  push:
    <<: *defaults

    steps:
      - attach_workspace:
          at: workspace
      - setup_remote_docker

      - run:
          name: "Log in to dockerhub"
          command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

      - run:
          name: "Reload and push docker image"
          command: |
            docker load < workspace/image/$CIRCLE_PROJECT_REPONAME-image.tar
            set -x `docker inspect --format '{{.Config.Labels.repouser}} {{.Config.Labels.name}} {{.Config.Labels.version}}' $CIRCLE_PROJECT_REPONAME:latest`
            docker tag $CIRCLE_PROJECT_REPONAME:latest $1/$2:latest
            docker tag $CIRCLE_PROJECT_REPONAME:latest $1/$2:$3
            docker push $1/$2:latest
            docker push $1/$2:$3+ansible$4

workflows:
  version: 2
  build-push:
    jobs:
      - build:
          context: sweg
          filters:
            tags:
              ignore: /^\d+\.\d+\.\d+([-+].*)?$/

      - push:
          context: sweg
          requires:
            - build
          filters:
            tags:
              only: /^\d+\.\d+\.\d+([-+].*)?$/
